services:
    loki:
      image: grafana/loki:2.9.4
      container_name: loki
      ports:
        - "3100:3100"
      command: -config.file=/etc/loki/local-config.yaml
      volumes:
        - ./loki-config.yaml:/etc/loki/local-config.yaml
      restart: unless-stopped
    grafana:
      image: grafana/grafana:10.2.3
      container_name: grafana
      ports:
        - "3000:3000"
      environment:
        - ${GRAFANA_USER}
        - ${GRAFANA_USER_PASSWORD}
      depends_on:
        - loki
      restart: unless-stopped
    api:
      image: immo-api:latest
      container_name: api
      build:
        context: .
        dockerfile: backend/api/Dockerfile
      environment:
        DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
        BASE_URL: ${BASE_URL}
        LOKI_URL: http://loki:3100
      ports:
        - "8000:8000"
      volumes:
        - .:/app
    worker_loop:
      image: immo-worker:latest
      container_name: worker_loop
      build:
        context: .
        dockerfile: backend/worker/Dockerfile
      environment:
        DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
        LOKI_URL: http://loki:3100
      command: ["python", "-m", "backend.worker.job_loop"]
      restart: unless-stopped
    schedule_loop:
      image: immo-worker:latest
      container_name: schedule_loop
      build:
        context: .
        dockerfile: backend/worker/Dockerfile
      environment:
        DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
        LOKI_URL: http://loki:3100
      command: ["python", "-m", "backend.worker.schedule_loop"]
      restart: unless-stopped
    frontend:
      image: immo-frontend:latest
      container_name: frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "5173:5173"
      volumes:
        - ./frontend:/app
        - /app/node_modules
      depends_on:
        - api
      restart: unless-stopped
    mysql:
      image: mysql:8.0
      volumes:
        - mysql_data:/var/lib/mysql
      ports:
        - 3306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_MYSQL_PASSWORD}
    zenml:
      image: zenmldocker/zenml-server:0.94.1-arm64
      ports:
        - "8080:8080"
      environment:
        - ZENML_STORE_URL=mysql://root:${DB_MYSQL_PASSWORD}@mysql/zenml
      depends_on:
        - mysql
      restart: on-failure
    minio:
      restart: always
      image: minio/minio@sha256:86b3e1b2892ad7f3a67add9791415e91f22f1affababfc04793bf68143a3c28f
      platform: linux/arm64
      container_name: mlflow_s3
      ports:
        - "9000:9000"
        - "9001:9001"
      command: server /data --console-address ":9001" --address ":9000"
      environment:
        - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
        - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
      volumes:
        - minio_data:/data

    mc:
      image: minio/mc@sha256:68d8c80f43908b02daa285e55547131870a1d36b3ffe272c26d7d8f4d52d1e5c
      depends_on:
        - minio
      container_name: mc
      env_file:
        - .env
      entrypoint: >
        /bin/sh -c "
        /tmp/wait-for-it.sh minio:9000 &&
        /usr/bin/mc alias set minio http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} &&
        /usr/bin/mc mb --ignore-existing minio/mlflow;
        exit 0;
        "
      volumes:
        - ./wait-for-it.sh:/tmp/wait-for-it.sh

    mlflow:
      restart: always
      image: ghcr.io/mlflow/mlflow:latest
      container_name: mlflow_server
      depends_on:
        - mc
      ports:
        - "5000:5000"
      environment:
        - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - MLFLOW_SERVER_CORS_ALLOWED_ORIGINS=http://192.168.178.28:5000
      extra_hosts:
        - "host.docker.internal:host-gateway"
      command: >
        mlflow server
        --backend-store-uri ${DB_CONNECTION_STRING_MLFLOW}
        --default-artifact-root s3://mlflow/
        --host 0.0.0.0
        --port 5000
volumes:
  mysql_data:
  minio_data: