services:
    scraper:
      image: immo-scraper:latest
      container_name: scraper
      build:
        context: .
        dockerfile: scraper/Dockerfile
      environment:
        DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
        LOKI_URL: http://loki:3100
      depends_on:
        - loki
    crawler:
      image: immo-crawler:latest
      container_name: crawler
      build:
        context: .
        dockerfile: crawler/Dockerfile
      environment:
        DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
        LOKI_URL: http://loki:3100
      depends_on:
        - loki
    loki:
      image: grafana/loki:2.9.4
      container_name: loki
      ports:
        - "3100:3100"
      command: -config.file=/etc/loki/local-config.yaml
      volumes:
        - ./loki-config.yaml:/etc/loki/local-config.yaml
      restart: unless-stopped
    grafana:
      image: grafana/grafana:10.2.3
      container_name: grafana
      ports:
        - "3000:3000"
      environment:
        - ${GRAFANA_USER}
        - ${GRAFANA_USER_PASSWORD}
      depends_on:
        - loki
      restart: unless-stopped
    api:
      image: immo-api:latest
      container_name: api
      build:
        context: .
        dockerfile: core/api/Dockerfile
      environment:
        DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      ports:
        - "8000:8000"
    worker_loop:
      image: immo-worker_loop:latest
      container_name: worker_loop
      build:
        context: .
        dockerfile: core/worker/Dockerfile
      environment:
        DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}

