"""Init migartion

Revision ID: 9173ded3413b
Revises: 
Create Date: 2026-05-31 14:52:32.885521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9173ded3413b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_results', sa.Column('property_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_search_result_property', 'search_results', ['search_params_id', 'property_id'])
    op.create_foreign_key(None, 'search_results', 'property', ['property_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search_results', type_='foreignkey')
    op.drop_constraint('uq_search_result_property', 'search_results', type_='unique')
    op.drop_column('search_results', 'property_id')
    # ### end Alembic commands ###
