"""alter add_type

Revision ID: 926498f0582e
Revises: cca9200a2aea
Create Date: 2026-06-11 12:35:29.498985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926498f0582e'
down_revision: Union[str, Sequence[str], None] = 'cca9200a2aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('ad_type', sa.String(), server_default='OFFERED', nullable=True))
    op.add_column('houses', sa.Column('ad_type', sa.String(), server_default='OFFERED', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'ad_type')
    op.drop_column('apartments', 'ad_type')
    # ### end Alembic commands ###
