name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: Deploy locally on Raspberry Pi
        run: |
          cd /home/konwo/Coding/Python/immo_scraper
          git pull
          docker compose up -d --build